-- AlterTable
ALTER TABLE "brand" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "category" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "product" ALTER COLUMN "title" SET DATA TYPE TEXT,
ALTER COLUMN "features" SET DATA TYPE TEXT[],
ALTER COLUMN "specifications" SET DATA TYPE TEXT,
ALTER COLUMN "images" SET DATA TYPE TEXT[],
ALTER COLUMN "url_source" SET DATA TYPE TEXT;
